**Numpy 공부 3**

In [1]:
import numpy as np

**ndarray.shape : 배열의 각 축(axis)의 크기<br>
ndarray.ndim : 축의 개수(Dimension)<br>
ndarray.dtype : 각 요소(Element)의 타입<br>
ndarray.itemsize : 각 요소(Element)의 타입의 bytes 크기<br>
ndarray.size : 전체 요소(Element)의 개수<br>**

In [2]:
# 0이상, 15미만의 수를 shape가 (3,5)인 배열 생성
a = np.arange(15).reshape(3,5)

In [3]:
print(a)
# 배열의 각 축의 크기
print(a.shape)
# 축의 개수
print(a.ndim)
# 각 요소의 타입의 byte크기
print(a.itemsize)
# 전체 요소의 개수
print(a.size)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
(3, 5)
2
4
15


**편하게 배열 생성하기**

In [4]:
# shape가 (3,4)인 배열을 생성해서 0으로 채움
print(np.zeros((3,4)))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [5]:
# shape가 (2,3,4)인 배열을 int16형인 1로 채움
# (2,3,4) -> (3,4)인 배열을 2개 생성
print(np.ones((2,3,4), dtype = np.int16))

[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]


In [6]:
# shape가 (2,3)인 배열을 초기화되지 않은 값으로 채움
print(np.empty((2,3)))

[[1.39069238e-309 1.39069238e-309 1.39069238e-309]
 [1.39069238e-309 1.39069238e-309 1.39069238e-309]]


**연속적인 데이터 생성<br>**
np.arange() : N만큼 차이나는 숫자 생성<br>
np.linspace() : N 등분한 숫자 생성

In [7]:
# 10이상 30미만까지 5씩 차이나게 생성
print(np.arange(10,30,5))

[10 15 20 25]


In [8]:
# 0이상 99까지 100등분해서 생성
print(np.linspace(0,99,100))

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17.
 18. 19. 20. 21. 22. 23. 24. 25. 26. 27. 28. 29. 30. 31. 32. 33. 34. 35.
 36. 37. 38. 39. 40. 41. 42. 43. 44. 45. 46. 47. 48. 49. 50. 51. 52. 53.
 54. 55. 56. 57. 58. 59. 60. 61. 62. 63. 64. 65. 66. 67. 68. 69. 70. 71.
 72. 73. 74. 75. 76. 77. 78. 79. 80. 81. 82. 83. 84. 85. 86. 87. 88. 89.
 90. 91. 92. 93. 94. 95. 96. 97. 98. 99.]


**배열의 shape 변경**<br>
reshape() : 배열의 데이터는 유지한 채 원하는 shape으로 변경한다.

In [9]:
# 1차원 배열 생성
print(np.arange(12))

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [10]:
# 배열의 shape을 (3,4)로 변경
print(np.arange(12).reshape(3,4))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [11]:
# (3,4) shape의 배열을 2개로 분할
print(np.arange(24).reshape(2,3,4))

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


**행렬 연산**<br>
@ : 행렬 곱셈<br>
.dot() : 행렬 내적

In [12]:
a = np.array([[1,1],[0,1]])
b = np.array([[2,0],[3,4]])

In [13]:
# 행렬 곱셈 연산
print(a @ b)

[[5 4]
 [3 4]]


In [14]:
# 행렬 내적 연산
print(a.dot(b))

[[5 4]
 [3 4]]


**그 외 연산들**<br>
np.array.sum(): 모든 요소의 합<br>
np.array.min(): 모든 요소 중 최소값<br>
np.array.max(): 모든 요소 중 최대값<br>
np.array.argmax(): 모든 요소 중 최대값의 인덱스<br>
np.array.cumsum(): 모든 요소의 누적합<br>

In [15]:
c = np.arange(8).reshape(2, 4) ** 2

In [16]:
print(c)

[[ 0  1  4  9]
 [16 25 36 49]]


In [17]:
# 모든 요소들의 합
print(c.sum())

140


In [18]:
# 모든 요소 중에 최소값
print(c.min())

0


In [19]:
# 모든 요소 중에 최대값
print(c.max())

49


In [20]:
# 모든 요소 중 최대값의 인덱스
print(c.argmax())

7


In [21]:
# 모든 요소의 누적합
print(c.cumsum())

[  0   1   5  14  30  55  91 140]


In [22]:
# axis를 사용해서 연산 기준 행렬을 지정해주고 연산도 가능함.
# axis = 0 : 열 기준 
# axis = 1 : 행 기준
print(c.sum(axis=0))
print(c.sum(axis=1))

[16 26 40 58]
[ 14 126]


**범용 함수**<br>
1. exp() : exponential
2. sqrt() : 제곱근 계산

In [23]:
d = np.arange(3)
print(d)

[0 1 2]


In [24]:
# y = e^x
print(np.exp(d))

[1.         2.71828183 7.3890561 ]


In [25]:
# y = sqrt(x)
print(np.sqrt(d))

[0.         1.         1.41421356]
