In [1]:
import numpy as np

**1. Array 정의**

In [2]:
# 일반 python 리스트 정의
data = [1,2,3,4,5]
data

[1, 2, 3, 4, 5]

In [3]:
# 일반 python 리스트 정의
data2 = [1,2,3,3.5,4]
data2

[1, 2, 3, 3.5, 4]

In [4]:
# numpy를 이용해서 array 정의
# 위에서 정의한 python list를 이용
arr = np.array(data)
arr

array([1, 2, 3, 4, 5])

In [5]:
# array의 형태(크기)를 확인
arr.shape

(5,)

In [6]:
# 바로 리스틀르 넣어줌으로써 array 만들기
arr2 = np.array([1,2,3,4,5])
arr2

array([1, 2, 3, 4, 5])

In [7]:
arr2.shape

(5,)

In [8]:
# array의 자료형을 확인
arr2.dtype

dtype('int32')

In [9]:
arr3 = np.array(data2)
arr3

array([1. , 2. , 3. , 3.5, 4. ])

In [10]:
arr3.shape

(5,)

In [11]:
arr3.dtype

dtype('float64')

In [12]:
arr4 = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
arr4

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [13]:
arr4.shape

(4, 3)

**numpy shape**<br>
np.shape로 해당 array의 크기를 확인할 수 있다.<br>
shape를 확인함으로써 몇개의 데이터가 몇차원으로 존재하는지를 알 수 있다.<br>
위에서 확인한 aar2.shape는 (5,)으로 1차원 데이터이고 5개의 요소가 있다는 것을 확인할 수 있다.<br>
aar4의 shape는 (4,3)으로 2차원 데이터로 4행3열의 크기를 갖고 있다는 것을 알 수 있다.

**numpy dtype**<br>
앞에서 살펴본 arr, arr2는 정수만 포함된 array의 자료형으로 'int32'으로 확인이 가능하며<br>
요소들 중 실수가 표함된 arr3의 경우 float64로 나타난다.<br>

**2. np.zeors(), np.ones(), np.arrange() 함수**<br>
numpy에서는 편하게 array를 생성하는 메소드를 지원한다.

In [14]:
# 요소가 0인 array 데이터 생성
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [15]:
# 요소가 0인 4*3 array 데이터 생성
np.zeros((4,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [16]:
# 요소가 1인 array 데이터 생성
np.ones(9)

array([1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [17]:
# 요소가 1인 4*3 크기의 array 데이터 생성
np.ones((4,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [18]:
# 0 ~ 9의 요소를 가진 array 데이터 생성
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
# 3 ~ 10의 요소를 가진 array 데이터 생성
np.arange(3, 10+1)

array([ 3,  4,  5,  6,  7,  8,  9, 10])

**3. array 연산**<br>
numpy array 간 연산 시 동일한 크기의 데이터끼리 연산이 가능하며 같은 위치에 있는 요소끼리 연산된다.

In [20]:
arr1 = np.array([[1,2,3],[4,5,6]])
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [21]:
arr2 = np.array([[10,11,12],[13,14,15]])
arr2

array([[10, 11, 12],
       [13, 14, 15]])

In [22]:
arr1.shape
arr2.shape

(2, 3)

In [23]:
# array 덧셈
arr1 + arr2

array([[11, 13, 15],
       [17, 19, 21]])

In [24]:
# array 곱셈
arr1 * arr2

array([[10, 22, 36],
       [52, 70, 90]])

In [25]:
# array 뺼셈
arr1 - arr2

array([[-9, -9, -9],
       [-9, -9, -9]])

In [26]:
# array 나눗셈
arr1 / arr2

array([[0.1       , 0.18181818, 0.25      ],
       [0.30769231, 0.35714286, 0.4       ]])

**4. array 연산 2 - 브로드캐스팅**<br>
numpy에서 array 연산 중 브로드캐스팅 방식의 연산이 가능하다.<br>
서로 다른 크기의 array를 연산할 수 있다는 뜻이며 아래 예를 통해 확인할 수 있다.

In [27]:
arr3 = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
arr3

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [28]:
arr4 = np.array([[10,10,10]])
arr4

array([[10, 10, 10]])

In [29]:
arr3.shape

(4, 3)

In [30]:
arr4.shape

(1, 3)

In [31]:
# 4*3 데이터에 1*3 데이터 더하기
arr3 + arr4

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19],
       [20, 21, 22]])

In [32]:
arr5 = np.array([[1]])
arr5

array([[1]])

In [33]:
# 4*3 데이터에 1*1 데이터 더하기
arr3 + arr5

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10],
       [11, 12, 13]])

In [34]:
arr6 = np.array([[1],[2],[3],[4]])
arr7 = np.array([[1,1,1,1]])

In [35]:
arr6

array([[1],
       [2],
       [3],
       [4]])

In [36]:
arr7

array([[1, 1, 1, 1]])

In [37]:
# 1*4 데이터와 4*1 데이터 더하기
arr6 + arr7

array([[2, 2, 2, 2],
       [3, 3, 3, 3],
       [4, 4, 4, 4],
       [5, 5, 5, 5]])

1*4 크기의 데이터와 4*1 크기의 데이터를 더하면
각 행에 4*4 크기의 데이터가 되며 그 값은 각 행의 값에 각 열의 값을 더해준 값이 된다

**5. array 생성 : np.full(shape, number, dtype)**<br>
full 메소드는 원하는 크기의 모든 값을 원하는 값, 원하는 데이터 타입으로 일괄 정의하는 기능을 한다.

In [38]:
# 1*10인 크기에 모든 값이 11인 데이터 형식은 float64를 가진 array를 생성한다
arr8 = np.full(10, 11, dtype=np.float64)
arr8

array([11., 11., 11., 11., 11., 11., 11., 11., 11., 11.])

In [39]:
# 크기가 5*5인 모든값이 100인 array를 생성한다.
arr9 = np.full((5,5),100)
arr9

array([[100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100]])